name: stepupdev
description: App to learn development framworks and languages

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  youtube_player_flutter: ^8.0.0
  http: ^0.13.4
  google_fonts: ^2.1.1
  provider:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
